name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установить зависимости
        run: pip install pyinstaller opencv-python numpy

      - name: Собрать EXE
        run: pyinstaller --onefile lab1/lab_video_part2.py

      - name: Сохранить EXE
        uses: actions/upload-artifact@v4
        with:
          name: lab_video_part2_exe
          path: dist/lab_video_part2.exe
